/**
 * Generates `server/replay.ts`, a Hono server that answers captured endpoints
 * from `recordings.json` and serves the built app from `./dist`.
 */
import type { ApiModel } from '../analysis/apiModel';

/** `/users/{id}` → `/users/:id`. */
export function templateToHonoPath(template: string): string {
  return template.replace(/\{([^}]+)\}/g, ':$1');
}

/**
 * The first path segment shared by observed endpoints, e.g. `/api`. Requests
 * under it that were never captured must fail loudly rather than fall through
 * to the SPA fallback, which would answer 200 with the app shell.
 */
function apiPrefixes(model: ApiModel): string[] {
  const prefixes = new Set<string>();
  for (const endpoint of model.endpoints) {
    const first = endpoint.template.split('/').filter(Boolean)[0];
    if (first && !first.startsWith('{')) prefixes.add(`/${first}`);
  }
  return Array.from(prefixes).sort();
}

/**
 * Source of the replay server. Route registration order is load-bearing:
 * literal endpoints, then static files, then param endpoints, then 501 guards
 * for uncaptured paths under an observed API prefix, then the SPA fallback.
 * Each endpoint always replays its first recording, keyed by `endpointKey`,
 * and a missing recording answers 501 `RAIDR-GAP` rather than inventing data.
 * The server listens on `PORT`, default 8787.
 *
 * raidr_cli's `--replay` mirror mode rewrites this output with exact-string
 * `.replace()` calls (in its src/commands/reconstruct.ts) on
 * `const app = new Hono();`, the `./dist` static and fallback lines, and the
 * body of `respond`. Editing those lines here silently disables that mode.
 */
export function generateReplayServer(model: ApiModel): string {
  const route = (endpoint: ApiModel['endpoints'][number]) =>
    `app.${endpoint.method.toLowerCase()}('${templateToHonoPath(endpoint.template)}', (c) => respond(c, '${endpoint.key}'));`;

  // An exact path is unambiguous, so it can replay ahead of the static handler.
  // A path with a param is a pattern, and a pattern matches real files too:
  // `/{token}` becomes `/:token`, which swallows /favicon.ico and every other
  // top-level file in the mirror. Those wait until static has had its turn.
  const isPattern = (endpoint: ApiModel['endpoints'][number]) =>
    endpoint.template.includes('{');

  const literalRoutes = model.endpoints.filter((e) => !isPattern(e)).map(route).join('\n');
  const patternRoutes = model.endpoints.filter(isPattern).map(route).join('\n');

  const gapGuards = apiPrefixes(model)
    .map(
      (prefix) =>
        `app.all('${prefix}/*', (c) =>\n  c.json(\n    { error: 'RAIDR-GAP', detail: \`no endpoint captured for \${c.req.method} \${c.req.path}\` },\n    501\n  )\n);`
    )
    .join('\n');

  return `// Generated by raidr. Replays responses captured from the original app.
import { Hono } from 'hono';
import { serveStatic } from 'hono/bun';
import type { Context } from 'hono';
import recordings from './recordings.json';

type Recording = { status: number; headers: Record<string, string>; body: unknown };

const app = new Hono();

function respond(c: Context, key: string) {
  const recorded = (recordings as Record<string, Recording[]>)[key];
  if (!recorded || recorded.length === 0) {
    // RAIDR-GAP: no response was captured for this endpoint. Failing loudly is
    // deliberate — inventing one would make the reconstruction quietly wrong.
    return c.json(
      { error: 'RAIDR-GAP', detail: \`no captured response for \${key}\` },
      501
    );
  }
  const pick = recorded[0]!;
  return c.json(pick.body as never, pick.status as never);
}

${literalRoutes}

// Static assets first: an endpoint prefix like /hologram can also be a real
// content directory, and a file that exists must always win over a guard.
app.use('/*', serveStatic({ root: './dist' }));

// Param routes only now: /:token matches every single-segment path, so it
// would swallow /favicon.ico and the rest of the mirror if it were registered
// above. It still has to precede the gap guards below, or /api/* answers 501
// for an endpoint that was actually captured.
${patternRoutes}

// Only then: paths under an observed API prefix that were never captured.
// Answering these with the SPA shell would look like success; 501 says what is
// actually true.
${gapGuards}

// Finally the SPA fallback, so client-side routes resolve on reload.
app.get('*', serveStatic({ path: './dist/index.html' }));

const port = Number(process.env.PORT ?? 8787);
export default { port, fetch: app.fetch };
`;
}
